# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
- url: "/api"

paths:
  /ai:
    get:
      operationId: "AI_API.create_agent_and_env"
      summary: "Create an agent and an env"
      responses:
        "200":
          description: "Successfully created agent and env"
    post:
      operationId: "AI_API.return_move"
      summary: "Place a move, receive a move back"
      requestBody:
        description: "Provide move data"
        required: true
        content:
          application/json:
            schema:
              x-body-name: "move_data"
              $ref: "#/components/schemas/MoveData"
      responses:
        "201":
          description: "Request processed successfully"

components:
  schemas:
    MoveData:
      type: "object"
      required:
        - state
        - id
      properties:
        state:
          type: "array"
          items:
            type: "number"
          minItems: 4
          maxItems: 4
        id:
          type: "number"
